spring:
  datasource:
    url: jdbc:h2:mem:seubanco
    driverClassName: org.h2.Driver
    username: sadu
    password: sadu
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
